Use the latest version of grunt-karma and karma
karma 12.21 and grunt-karma don't play nice together and cause the error
below:

    WARN [preprocess]: Can not load "webpack"!
      TypeError: this.emitter.refreshFiles is not a function

Signed-off-by: Yuki Nishijima <ynishijima@pivotal.io>